### ISSUE TITLE
system\library\paytabs_api.php

### ISSUE THREAD

**Issue by opencartarab** [paytabscom/paytabs-opencart#27]
opencart-3.x
please check line: 576

**Comment by wajihkm** [comment]
Hi,
What is the issue?

**Comment by opencartarab** [comment]
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /home/***/public_html/system/library/paytabs_api.php on line 576

**Comment by wajihkm** [comment]
What is your PHP version?

**Comment by opencartarab** [comment]
php 7.3
opencart 3.0.3.6
paytabs-opencart opencart-3.x

**Comment by wajihkm** [comment]
This line is using "Arrow Functions".
https://www.php.net/manual/en/functions.arrow.php

Arrow functions became available since PHP 7.4.0.

**Comment by wajihkm** [comment]
You may check the latest commit.
Thanks.
