### ISSUE TITLE
Transaction ID is missing

### ISSUE THREAD

**Issue by mostafatarekssayed** [paytabscom/paytabs-opencart#8]
after payment, I get this 
msg in opencart
Transaction ID is missing
even the transaction is shown in paytabs dashboard 
but it is not created in opencart dashboard

![image](https://user-images.githubusercontent.com/26235388/116802492-8b04ad80-ab13-11eb-9fb2-c7c6fcc1e5b0.png)

**Comment by wajihkm** [comment]
Hi @mostafatarekssayed 
Most probably, The website URL is not HTTPS, kindly check.

Thanks,
Wajih
